package com.cloudsimulator.gui;

import com.cloudsimulator.config.DatacenterConfig;
import com.cloudsimulator.config.HostConfig;
import com.cloudsimulator.enums.ComputeType;
import com.cloudsimulator.enums.WorkloadType;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Writer for generating .cosc configuration files from ExperimentTemplate.
 * Supports generating multiple files with different seeds where task instruction
 * lengths vary based on the seed.
 */
public class CosmosConfigWriter {

    private static final DateTimeFormatter DATE_TIME_FORMATTER =
        DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");

    /**
     * Generates multiple .cosc files with seeds in the specified range.
     * Each file will have identical datacenters, hosts, users, VMs, and task distribution,
     * but task instruction lengths will vary based on the seed.
     *
     * @param template The experiment template
     * @param startSeed Starting seed value (inclusive)
     * @param endSeed Ending seed value (inclusive)
     * @param outputDir Directory to write files to
     * @return List of generated file paths
     * @throws IOException If writing fails
     */
    public List<File> generateConfigs(ExperimentTemplate template, long startSeed,
                                       long endSeed, File outputDir) throws IOException {
        List<File> generatedFiles = new ArrayList<>();

        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }

        String timestamp = LocalDateTime.now().format(DATE_TIME_FORMATTER);

        for (long seed = startSeed; seed <= endSeed; seed++) {
            String fileName = String.format("%d_%s_%03d.cosc", seed, timestamp, seed - startSeed + 1);
            File outputFile = new File(outputDir, fileName);

            writeConfigFile(template, seed, outputFile);
            generatedFiles.add(outputFile);
        }

        return generatedFiles;
    }

    /**
     * Writes a single .cosc configuration file.
     */
    public void writeConfigFile(ExperimentTemplate template, long seed, File outputFile) throws IOException {
        Random random = new Random(seed);

        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            // Write header comment
            writer.println("# Cosmos Configuration File (.cosc)");
            writer.println("# Generated by ConfigGeneratorApp");
            writer.println("# Seed: " + seed);
            writer.println("# Generated: " + LocalDateTime.now());
            writer.println();

            // Write SEED section
            writeSeedSection(writer, seed);

            // Write DATACENTERS section
            writeDatacentersSection(writer, template.getDatacenterConfigs());

            // Write HOSTS section
            writeHostsSection(writer, template.getHostConfigs());

            // Write USERS section
            writeUsersSection(writer, template.getUserTemplates());

            // Write VMS section
            writeVMsSection(writer, template.getUserTemplates());

            // Write TASKS section
            writeTasksSection(writer, template.getUserTemplates(), random);
        }
    }

    private void writeSeedSection(PrintWriter writer, long seed) {
        writer.println("[SEED]");
        writer.println(seed);
        writer.println();
    }

    private void writeDatacentersSection(PrintWriter writer, List<DatacenterConfig> datacenters) {
        writer.println("[DATACENTERS]");
        writer.println(datacenters.size());
        for (DatacenterConfig dc : datacenters) {
            writer.printf("%s,%d,%.1f%n",
                dc.getName(), dc.getMaxHostCapacity(), dc.getTotalMaxPowerDraw());
        }
        writer.println();
    }

    private void writeHostsSection(PrintWriter writer, List<HostConfig> hosts) {
        writer.println("[HOSTS]");
        writer.println(hosts.size());
        for (HostConfig host : hosts) {
            writer.printf("%d,%d,%s,%d,%d,%d,%d,%s%n",
                host.getInstructionsPerSecond(),
                host.getNumberOfCpuCores(),
                host.getComputeType().name(),
                host.getNumberOfGpus(),
                host.getRamCapacityMB(),
                host.getNetworkCapacityMbps(),
                host.getHardDriveCapacityMB(),
                host.getPowerModelName());
        }
        writer.println();
    }

    private void writeUsersSection(PrintWriter writer, List<UserTemplate> users) {
        writer.println("[USERS]");
        writer.println(users.size());

        for (UserTemplate user : users) {
            StringBuilder line = new StringBuilder();
            line.append(user.getName()).append(",");

            // Datacenters as pipe-separated
            line.append(String.join("|", user.getSelectedDatacenterNames())).append(",");

            // Count VMs by type
            int gpuVMs = 0, cpuVMs = 0, mixedVMs = 0;
            for (VMTemplate vm : user.getVmTemplates()) {
                switch (vm.getComputeType()) {
                    case GPU_ONLY: gpuVMs++; break;
                    case CPU_ONLY: cpuVMs++; break;
                    case CPU_GPU_MIXED: mixedVMs++; break;
                }
            }
            line.append(gpuVMs).append(",").append(cpuVMs).append(",").append(mixedVMs).append(",");

            // Task counts by workload type (in order)
            Map<WorkloadType, Integer> taskCounts = new LinkedHashMap<>();
            for (WorkloadType wt : WorkloadType.values()) {
                if (wt != WorkloadType.IDLE) {
                    taskCounts.put(wt, 0);
                }
            }

            for (TaskTemplate task : user.getTaskTemplates()) {
                if (task.getWorkloadType() != WorkloadType.IDLE) {
                    taskCounts.merge(task.getWorkloadType(), task.getCount(), Integer::sum);
                }
            }

            // Write counts in order: SEVEN_ZIP, DATABASE, FURMARK, IMAGE_GEN_CPU, IMAGE_GEN_GPU,
            // LLM_CPU, LLM_GPU, CINEBENCH, PRIME95SmallFFT, VERACRYPT
            List<WorkloadType> orderedTypes = Arrays.asList(
                WorkloadType.SEVEN_ZIP, WorkloadType.DATABASE, WorkloadType.FURMARK,
                WorkloadType.IMAGE_GEN_CPU, WorkloadType.IMAGE_GEN_GPU,
                WorkloadType.LLM_CPU, WorkloadType.LLM_GPU,
                WorkloadType.CINEBENCH, WorkloadType.PRIME95SmallFFT,
                WorkloadType.VERACRYPT
            );

            StringJoiner sj = new StringJoiner(",");
            for (WorkloadType wt : orderedTypes) {
                sj.add(String.valueOf(taskCounts.getOrDefault(wt, 0)));
            }
            line.append(sj.toString());

            writer.println(line);
        }
        writer.println();
    }

    private void writeVMsSection(PrintWriter writer, List<UserTemplate> users) {
        writer.println("[VMS]");

        // Group VMs by compute type
        Map<ComputeType, List<VMWithUser>> vmsByType = new LinkedHashMap<>();
        vmsByType.put(ComputeType.GPU_ONLY, new ArrayList<>());
        vmsByType.put(ComputeType.CPU_ONLY, new ArrayList<>());
        vmsByType.put(ComputeType.CPU_GPU_MIXED, new ArrayList<>());

        for (UserTemplate user : users) {
            for (VMTemplate vm : user.getVmTemplates()) {
                vmsByType.get(vm.getComputeType()).add(new VMWithUser(vm, user.getName()));
            }
        }

        // Write each type
        for (Map.Entry<ComputeType, List<VMWithUser>> entry : vmsByType.entrySet()) {
            if (!entry.getValue().isEmpty()) {
                String typeLabel = getVMTypeLabel(entry.getKey());
                writer.printf("%s:%d%n", typeLabel, entry.getValue().size());

                for (VMWithUser vmWithUser : entry.getValue()) {
                    VMTemplate vm = vmWithUser.vm;
                    writer.printf("%s,%d,%d,%d,%d,%d,%d%n",
                        vmWithUser.userName,
                        vm.getRequestedIpsPerVcpu(),
                        vm.getRequestedVcpuCount(),
                        vm.getRequestedGpuCount(),
                        vm.getRequestedRamMB(),
                        vm.getRequestedStorageMB(),
                        vm.getRequestedBandwidthMbps());
                }
            }
        }
        writer.println();
    }

    private String getVMTypeLabel(ComputeType type) {
        switch (type) {
            case GPU_ONLY: return "GPU";
            case CPU_ONLY: return "CPU";
            case CPU_GPU_MIXED: return "MIXED";
            default: return "CPU";
        }
    }

    private void writeTasksSection(PrintWriter writer, List<UserTemplate> users, Random random) {
        writer.println("[TASKS]");

        // Group tasks by workload type
        Map<WorkloadType, List<TaskWithUser>> tasksByType = new LinkedHashMap<>();
        for (WorkloadType wt : WorkloadType.values()) {
            if (wt != WorkloadType.IDLE) {
                tasksByType.put(wt, new ArrayList<>());
            }
        }

        // Expand task templates and generate instruction lengths based on seed
        for (UserTemplate user : users) {
            for (TaskTemplate taskTemplate : user.getTaskTemplates()) {
                if (taskTemplate.getWorkloadType() == WorkloadType.IDLE) continue;

                for (int i = 0; i < taskTemplate.getCount(); i++) {
                    // Generate random instruction length within range
                    long instructionLength = generateInstructionLength(
                        taskTemplate.getMinInstructionLength(),
                        taskTemplate.getMaxInstructionLength(),
                        random);

                    String taskName = String.format("%s_%s_%d",
                        taskTemplate.getNamePrefix(),
                        user.getName(),
                        i + 1);

                    TaskWithUser task = new TaskWithUser(
                        taskName, user.getName(), instructionLength, taskTemplate.getWorkloadType());

                    tasksByType.get(taskTemplate.getWorkloadType()).add(task);
                }
            }
        }

        // Write tasks by type
        for (Map.Entry<WorkloadType, List<TaskWithUser>> entry : tasksByType.entrySet()) {
            if (!entry.getValue().isEmpty()) {
                writer.printf("%s:%d%n", entry.getKey().name(), entry.getValue().size());

                for (TaskWithUser task : entry.getValue()) {
                    writer.printf("%s,%s,%d%n",
                        task.name, task.userName, task.instructionLength);
                }
            }
        }
    }

    private long generateInstructionLength(long min, long max, Random random) {
        if (min >= max) {
            return min;
        }
        return min + (long) (random.nextDouble() * (max - min));
    }

    // Helper classes
    private static class VMWithUser {
        VMTemplate vm;
        String userName;

        VMWithUser(VMTemplate vm, String userName) {
            this.vm = vm;
            this.userName = userName;
        }
    }

    private static class TaskWithUser {
        String name;
        String userName;
        long instructionLength;
        WorkloadType workloadType;

        TaskWithUser(String name, String userName, long instructionLength, WorkloadType workloadType) {
            this.name = name;
            this.userName = userName;
            this.instructionLength = instructionLength;
            this.workloadType = workloadType;
        }
    }
}
