#!/usr/bin/env python3
"""
Pareto Front Plotter for JavaCloudSimulatorCosmos

This script generates 2D Pareto front visualizations from CSV data
produced by FlexibleExperimentMain.java.

Features:
    - Reads configuration from plot_options.json (generated by Java)
    - Distinct colors for each algorithm (both points and lines)
    - Universal Pareto front in red with smaller markers
    - XMode: Filter single-objective points to Universal Pareto only
    - Algorithm display name mapping for cleaner legends
    - Configurable DPI, figure size, marker size, and more

Usage:
    python pareto_plotter.py <reports_directory>

Example:
    python pareto_plotter.py reports/config_1_seed_42
    python pareto_plotter.py reports  # Processes all config folders

Requirements:
    pip install matplotlib pandas
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sys
import os
import json
from pathlib import Path
from typing import Dict, List, Optional, Any

# =============================================================================
# DEFAULT CONFIGURATION (overridden by plot_options.json if present)
# =============================================================================

DEFAULT_CONFIG = {
    'dpi': 300,
    'width': 14,
    'height': 10,
    'marker_size': 10,
    'marker_shape': 'circle',
    'show_legend': True,
    'show_labels': False,
    'xmode': False,
}

# =============================================================================
# ALGORITHM STYLING
# =============================================================================

# Distinct colors for each algorithm (used for both points and lines)
ALGORITHM_COLORS = {
    'FirstAvailable':   '#1f77b4',   # Blue
    'ShortestQueue':    '#ff7f0e',   # Orange
    'WorkloadAware':    '#2ca02c',   # Green
    'GA':               '#9467bd',   # Purple
    'SA':               '#8c564b',   # Brown
    'LocalSearch':      '#e377c2',   # Pink
    'MOEA_NSGAII':      '#17becf',   # Cyan
    'MOEA_SPEA2':       '#bcbd22',   # Yellow-green
    'MOEA_MOEAD':       '#7f7f7f',   # Gray
    'MOEA_OMOPSO':      '#d62728',   # Dark red (different from Universal)
    'MOEA_AMOSA':       '#98df8a',   # Light green
}

# Universal Pareto is always red
UNIVERSAL_PARETO_COLOR = '#FF0000'

# Marker shapes mapping
MARKER_SHAPES = {
    'circle': 'o',
    'square': 's',
    'triangle': '^',
    'diamond': 'D',
    'star': '*',
}

# Display names for algorithms (cleaner legend text)
ALGORITHM_DISPLAY_NAMES = {
    'FirstAvailable': 'First Available',
    'ShortestQueue': 'Shortest Queue',
    'WorkloadAware': 'Workload Aware',
    'GA': 'Genetic Algorithm',
    'SA': 'Simulated Annealing',
    'LocalSearch': 'Local Search',
    'MOEA_NSGAII': 'NSGA-II',
    'MOEA_SPEA2': 'SPEA2',
    'MOEA_MOEAD': 'MOEA/D',
    'MOEA_OMOPSO': 'OMOPSO',
    'MOEA_AMOSA': 'AMOSA',
    'Universal_Pareto': 'Universal Pareto',
}


def get_algorithm_color(algo_name: str) -> str:
    """Get color for an algorithm."""
    if algo_name == 'Universal_Pareto':
        return UNIVERSAL_PARETO_COLOR
    return ALGORITHM_COLORS.get(algo_name, '#000000')  # Default black


def get_display_name(algo_name: str) -> str:
    """Get display name for algorithm legend."""
    return ALGORITHM_DISPLAY_NAMES.get(algo_name, algo_name)


def get_marker(shape_name: str) -> str:
    """Get matplotlib marker from shape name."""
    return MARKER_SHAPES.get(shape_name, 'o')


# =============================================================================
# NON-DOMINANCE FILTERING
# =============================================================================

def is_dominated(point: np.ndarray, other_points: np.ndarray) -> bool:
    """
    Check if a point is dominated by any other point.
    A point is dominated if another point is at least as good in all objectives
    and strictly better in at least one.
    Both objectives are minimization (lower is better).
    """
    for other in other_points:
        if np.array_equal(other, point):
            continue
        if other[0] <= point[0] and other[1] <= point[1]:
            if other[0] < point[0] or other[1] < point[1]:
                return True
    return False


def get_non_dominated(points: np.ndarray) -> np.ndarray:
    """
    Filter points to return only non-dominated solutions.
    Returns points sorted by first objective (makespan).
    """
    if len(points) == 0:
        return np.array([])

    points = np.array(points)
    non_dominated = []

    for point in points:
        if not is_dominated(point, points):
            # Check for duplicates
            is_duplicate = False
            for nd in non_dominated:
                if abs(nd[0] - point[0]) < 1e-9 and abs(nd[1] - point[1]) < 1e-9:
                    is_duplicate = True
                    break
            if not is_duplicate:
                non_dominated.append(point)

    if len(non_dominated) == 0:
        return np.array([])

    non_dominated = np.array(non_dominated)
    sorted_indices = np.argsort(non_dominated[:, 0])
    return non_dominated[sorted_indices]


def is_in_universal_pareto(point: np.ndarray, universal_pareto: np.ndarray,
                           tolerance: float = 1e-6) -> bool:
    """Check if a point is in the Universal Pareto set."""
    for u in universal_pareto:
        if abs(u[0] - point[0]) < tolerance and abs(u[1] - point[1]) < tolerance:
            return True
    return False


# =============================================================================
# CONFIGURATION LOADING
# =============================================================================

def load_plot_options(target_dir: Path) -> Dict[str, Any]:
    """Load plot options from JSON file, falling back to defaults."""
    config = DEFAULT_CONFIG.copy()

    options_file = target_dir / 'plot_options.json'
    if options_file.exists():
        try:
            with open(options_file, 'r') as f:
                user_config = json.load(f)
                config.update(user_config)
                print(f'  Loaded plot options from {options_file}')
        except (json.JSONDecodeError, IOError) as e:
            print(f'  Warning: Could not load plot_options.json: {e}')

    return config


# =============================================================================
# PLOTTING FUNCTIONS
# =============================================================================

def plot_pareto_front(csv_path: str, output_path: str, config: Dict[str, Any]) -> None:
    """
    Generate Pareto front plot from CSV data.

    Features:
    - Each algorithm has distinct color (same for points and lines)
    - Each algorithm's non-dominated points are connected with a line
    - Universal Pareto front is shown in red with smaller markers

    Args:
        csv_path: Path to pareto_graph_data.csv
        output_path: Path for output PNG file
        config: Plot configuration dictionary
    """
    df = pd.read_csv(csv_path)

    fig, ax = plt.subplots(figsize=(config['width'], config['height']))

    # Get unique algorithms (excluding Universal_Pareto for now)
    algorithms = [a for a in df['Algorithm'].unique() if a != 'Universal_Pareto']

    # Get Universal Pareto points for XMode filtering
    universal_df = df[df['Algorithm'] == 'Universal_Pareto']
    universal_points = universal_df[['Makespan', 'Energy']].values if not universal_df.empty else np.array([])

    # Get marker settings
    marker = get_marker(config['marker_shape'])
    base_marker_size = config['marker_size']

    # Plot each algorithm's solutions with their Pareto line
    for algo in algorithms:
        algo_data = df[df['Algorithm'] == algo]
        color = get_algorithm_color(algo)
        display_name = get_display_name(algo)

        # Get all points for this algorithm
        points = algo_data[['Makespan', 'Energy']].values

        # XMode: Filter to only points in Universal Pareto
        if config['xmode'] and len(universal_points) > 0:
            points = np.array([p for p in points
                             if is_in_universal_pareto(p, universal_points)])
            if len(points) == 0:
                continue

        # Get non-dominated points for this algorithm
        non_dominated = get_non_dominated(points)

        # Plot non-dominated points and connecting line
        if len(non_dominated) > 0:
            # Draw line connecting non-dominated points (same color as points)
            if len(non_dominated) > 1:
                ax.plot(
                    non_dominated[:, 0],
                    non_dominated[:, 1],
                    color=color,
                    linewidth=2,
                    alpha=0.7,
                    linestyle='-',
                    zorder=2
                )

            # Draw points (same color as line)
            ax.scatter(
                non_dominated[:, 0],
                non_dominated[:, 1],
                c=color,
                marker=marker,
                s=base_marker_size ** 2,
                label=display_name,
                alpha=0.9,
                edgecolors='black',
                linewidths=0.5,
                zorder=3
            )

            # Add labels if enabled
            if config['show_labels']:
                for x, y in non_dominated:
                    ax.annotate(display_name, (x, y), textcoords="offset points",
                               xytext=(5, 5), fontsize=7, alpha=0.7)

    # Plot Universal Pareto (red, smaller markers)
    if len(universal_points) > 0:
        # Sort by makespan
        sorted_indices = np.argsort(universal_points[:, 0])
        universal_sorted = universal_points[sorted_indices]

        # Draw connecting line (red, thicker)
        ax.plot(
            universal_sorted[:, 0],
            universal_sorted[:, 1],
            color=UNIVERSAL_PARETO_COLOR,
            linewidth=2.5,
            alpha=0.9,
            linestyle='-',
            zorder=4
        )

        # Draw points (red, smaller than algorithm points)
        # Universal marker size is 60% of algorithm marker size
        universal_marker_size = base_marker_size * 0.6
        ax.scatter(
            universal_sorted[:, 0],
            universal_sorted[:, 1],
            c=UNIVERSAL_PARETO_COLOR,
            marker='o',
            s=universal_marker_size ** 2,
            label=get_display_name('Universal_Pareto'),
            edgecolors='darkred',
            linewidths=1,
            zorder=5
        )

    # Formatting
    ax.set_xlabel('Makespan (seconds)', fontsize=14)
    ax.set_ylabel('Energy (kWh)', fontsize=14)
    ax.set_title('Multi-Algorithm Pareto Front Comparison', fontsize=16, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.tick_params(axis='both', which='major', labelsize=11)

    if config['show_legend']:
        ax.legend(
            bbox_to_anchor=(1.05, 1),
            loc='upper left',
            fontsize=11,
            framealpha=0.95,
            edgecolor='black'
        )

    plt.tight_layout()
    plt.savefig(output_path, dpi=config['dpi'], bbox_inches='tight', facecolor='white')
    plt.close()

    print(f'  Generated: {output_path}')


def plot_metrics_comparison(csv_path: str, output_path: str, config: Dict[str, Any]) -> None:
    """
    Generate bar chart comparing performance metrics across algorithms.

    Args:
        csv_path: Path to performance_metrics.csv
        output_path: Path for output PNG file
        config: Plot configuration dictionary
    """
    df = pd.read_csv(csv_path)

    # Filter out Universal_Pareto for comparison
    df = df[df['Algorithm'] != 'Universal_Pareto']

    fig, axes = plt.subplots(1, 3, figsize=(16, 6))

    metrics = ['HV', 'GD', 'IGD']
    titles = ['Hypervolume (higher is better)', 'GD (lower is better)', 'IGD (lower is better)']

    for ax, metric, title in zip(axes, metrics, titles):
        # Get colors from ALGORITHM_COLORS
        colors = [get_algorithm_color(algo) for algo in df['Algorithm']]
        display_names = [get_display_name(algo) for algo in df['Algorithm']]

        bars = ax.bar(display_names, df[metric], color=colors, alpha=0.8, edgecolor='black')
        ax.set_title(title, fontsize=12, fontweight='bold')
        ax.set_ylabel(metric, fontsize=11)
        ax.tick_params(axis='x', rotation=45, labelsize=9)

        # Add value labels on bars
        for bar, val in zip(bars, df[metric]):
            height = bar.get_height()
            ax.annotate(
                f'{val:.4f}',
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 3),
                textcoords="offset points",
                ha='center',
                va='bottom',
                fontsize=8,
                fontweight='bold'
            )

    plt.tight_layout()
    plt.savefig(output_path, dpi=config['dpi'], bbox_inches='tight', facecolor='white')
    plt.close()

    print(f'  Generated: {output_path}')


# =============================================================================
# DIRECTORY PROCESSING
# =============================================================================

def process_directory(target_dir: str) -> int:
    """
    Process a directory containing experiment results.

    Args:
        target_dir: Path to directory containing CSV files

    Returns:
        Number of plots generated
    """
    target_path = Path(target_dir)
    plots_generated = 0

    # Check if this directory contains pareto_graph_data.csv
    pareto_csv = target_path / 'pareto_graph_data.csv'
    metrics_csv = target_path / 'performance_metrics.csv'

    if pareto_csv.exists():
        # Load configuration from this directory
        config = load_plot_options(target_path)

        output = target_path / 'pareto_front.png'
        plot_pareto_front(str(pareto_csv), str(output), config)
        plots_generated += 1

        if metrics_csv.exists():
            metrics_output = target_path / 'metrics_comparison.png'
            plot_metrics_comparison(str(metrics_csv), str(metrics_output), config)
            plots_generated += 1
    else:
        # Check subdirectories
        for folder in target_path.iterdir():
            if folder.is_dir():
                pareto_csv = folder / 'pareto_graph_data.csv'
                metrics_csv = folder / 'performance_metrics.csv'

                if pareto_csv.exists():
                    # Load configuration from this subdirectory
                    config = load_plot_options(folder)

                    output = folder / 'pareto_front.png'
                    plot_pareto_front(str(pareto_csv), str(output), config)
                    plots_generated += 1

                    if metrics_csv.exists():
                        metrics_output = folder / 'metrics_comparison.png'
                        plot_metrics_comparison(str(metrics_csv), str(metrics_output), config)
                        plots_generated += 1

    return plots_generated


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    target = sys.argv[1]

    if os.path.isfile(target) and target.endswith('.csv'):
        # Single CSV file - use default config
        config = DEFAULT_CONFIG.copy()

        if 'pareto_graph_data' in target:
            output = target.replace('.csv', '_pareto.png')
            plot_pareto_front(target, output, config)
        elif 'performance_metrics' in target:
            output = target.replace('.csv', '_comparison.png')
            plot_metrics_comparison(target, output, config)
        else:
            print(f"Unknown CSV format: {target}")
            print("Expected: pareto_graph_data.csv or performance_metrics.csv")
            sys.exit(1)

    elif os.path.isdir(target):
        plots = process_directory(target)
        if plots == 0:
            print(f"No pareto_graph_data.csv files found in {target}")
            sys.exit(1)
        print(f"\nTotal plots generated: {plots}")
    else:
        print(f"Error: {target} is not a valid file or directory")
        sys.exit(1)


if __name__ == '__main__':
    main()
